doctrine:
    dbal:
        #url: '%env(resolve:DATABASE_URL)%'
        dbname: dbs5063716
        host: db5006046034.hosting-data.io
        port: 3306
        user: dbu2522778
        password: SymfoPlaces01_$
        driver: pdo_mysql
        charset: UTF8
        server_version: mariadb-10.5.12
    # dbal:
    #     #url: '%env(resolve:DATABASE_URL)%'
    #     dbname: symfoplaces
    #     host: localhost
    #     port: 3306
    #     user: root
    #     password:
    #     driver: pdo_mysql
    #     charset: UTF8
    #     server_version: mariadb-10.4.13

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
