twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/public/css': styles
        '%kernel.project_dir%/public/img': images
    globals:
        places_directory: '%app.places%'
        users_pics_directory: '%app.users_pics%'
        # frase: '@App\Services\FrasesService'
        entityFaker: '@App\Services\EntityFakerService'
    # form_themes: [
    #     'widgets/data_list.html.twig']

when@test:
    twig:
        strict_variables: true
